### ISSUE TITLE
Add other APIs

### ISSUE THREAD

**Issue by ShintoKosei** [sametgirginer/XF2-MinecraftServerChecker#1]
This plugin is very useful, but it would be perfect if other APIs could be replaced. Because https://mcsrvstat.us/ is not so easy to use.
Hope to support open source self-buildable MinecraftServerChecker. This will be easier to use.

**Comment by sametgirginer** [comment]
I will bring update for API options soon.

**Comment by sametgirginer** [comment]
New update has arrived. 
[1.0.5](https://github.com/sametgirginer/XF2-MinecraftServerChecker/releases/tag/1.0.5)
